project:
  type: website
  execute-dir: file
  preview:
    browser: true
    watch-inputs: true
    navigate: true
  render:
    - "*.qmd"
    - "!README.md"
    - "!LICENSE.md"

website:
  title: "Akshat Dwivedi"
  favicon: favicon.png
  navbar:
    search: true
    collapse: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ad1729
      - icon: linkedin
        href: https://www.linkedin.com/in/akshatd/
      - icon: images
        href: https://500px.com/p/akshatdwivedi?view=photos
  page-navigation: true
  page-footer:
    center: "akshat.blog © 2022-2023 Akshat Dwivedi. Built with [Quarto](https://www.quarto.org) and [GitHub Pages](https://pages.github.com). Read the [license.](https://github.com/ad1729/ad1729.github.io/LICENSE.md)"
  repo-url: https://github.com/ad1729/ad1729.github.io
  repo-actions: [issue]

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
    highlight-style: github
