project:
  type: website
  execute-dir: file
  preview:
    port: 4500
    browser: false
    watch-inputs: true
    navigate: true
  render:
    - "*.qmd"
    - "!ignored.qmd"
    - "!ignored*.qmd"
    - "!ignored.ipynb"
    - "!README.md"
    - "!LICENSE.md"
  resources:
    - CNAME

website:
  title: "Akshat Dwivedi"
  favicon: favicon.png
  navbar:
    search: true
    collapse: true
    pinned: true
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ad1729
      - icon: linkedin
        href: https://www.linkedin.com/in/akshatd/
      - icon: images
        href: https://500px.com/p/akshatdwivedi?view=photos
  back-to-top-navigation: false
  page-navigation: true
  page-footer:
    center: "akshat.blog © 2022-2024 Akshat Dwivedi. Built with [Quarto](https://www.quarto.org) and [GitHub Pages](https://pages.github.com). Read the [license.](https://github.com/ad1729/ad1729.github.io/LICENSE.md)"
  repo-url: https://github.com/ad1729/ad1729.github.io
  repo-branch: master
  # repo-actions: [source, issue]
  repo-actions: [issue]

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
    highlight-style: github
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    footnotes-hover: true
    reference-location: margin
